# AWSClusterStaticIdentity references the secret cluster-identity-credentials, see README.md.
# The name "cluster-identity" is the default used by all ClusterClasses.
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSClusterStaticIdentity
metadata:
  name: cluster-identity
spec:
  secretRef: cluster-identity-credentials
  allowedNamespaces:
    list: []          # empty list means all namespaces are allowed
